DIVERSE_GENERAL_TEMPLATES = [
    # I. Simple Positional Variations
    "a detailed photo of {}",
    "{} in a natural setting",
    "the majestic {}",
    "an abstract view of {}",
    "{} under a bright light",
    "close-up shot of {}",
    "a vibrant illustration of {}",
    "{}, simple, clean background",
    "a stylized rendering of {}",
    "a dramatic portrait of {}",
    "{} on a pedestal",
    "a high-contrast image of {}",
    "{} at dawn",
    "the essence of {}",
    "a tiny {}",

    # II. Atmospheric & Lighting
    "an atmospheric image of {} bathed in moonlight",
    "{} illuminated by a single, warm spotlight",
    "a moody, film-noir style depiction of {}",
    "hazy sunlight filtering onto a solitary {}",
    "a chiaroscuro painting of {}",
    "{} silhouetted against a brilliant sunset sky",
    "neon glow reflecting off of {}",
    "a misty, ethereal shot of {}",
    "dynamic light streaks surrounding {}",
    "{} caught in a rainstorm, backlit",
    "a subtle, pastel-toned photograph of {}",
    "under the glow of a celestial body, {}",
    "deep shadows obscuring parts of {}",
    "a volumetric light ray hitting {}",
    "the eerie light of a full moon on {}",
    "soft window light illuminating the texture of {}",
    "{} at midnight, only streetlights visible",
    "golden hour lighting, capturing the beauty of {}",
    "a dark, saturated image of {}",
    "a flickering candlelight casting shadows on {}",

    # III. Artistic Medium & Style
    "{} as a hyper-realistic oil painting on canvas",
    "a rough pencil sketch of {}",
    "pointillism art of {} by Seurat",
    "a low-poly 3D render of {}",
    "{} in the style of Japanese woodblock print, ukiyo-e",
    "a digital speedpainting of {}",
    "stained glass window depicting {}",
    "{} sculpted from bronze, verdigris patina",
    "a psychedelic poster design featuring {}",
    "watercolor splash art of {}",
    "{} rendered in an Art Deco style",
    "a blueprint technical drawing of {}",
    "cross-hatching ink illustration of {}",
    "{} as a mosaic made of small, colorful tiles",
    "an abstract expressionist interpretation of {}",
    "detailed pixel art of {}",
    "{} reimagined as a Fauvist painting",
    "a photo-realistic C4D render of {}",
    "a charcoal drawing of {} on textured paper",
    "{} as a medieval illuminated manuscript detail",
    "geometric tessellation patterns forming {}",
    "{} in the style of a retro video game cover",
    "a Cubist deconstruction of {}",
    "{} created with layers of cut paper (papercraft)",
    "a Pop Art comic book panel of {}",

    # IV. Contextual & Narrative
    "{} exploring an ancient, overgrown ruin",
    "a peaceful moment where {} is observing a quiet landscape",
    "the aftermath of a dramatic event featuring {}",
    "{} standing on the peak of a snowy mountain",
    "a bustling marketplace scene with {} prominently displayed",
    "{} interacting with futuristic technology",
    "deep underwater, a strange {} drifts past",
    "an archaeological dig uncovering a fossilized {}",
    "{} surrounded by dozens of floating, glowing orbs",
    "on the surface of Mars, a lone {}",
    "{} defending a small village from a colossal threat",
    "a child's toy version of {} left on a playground swing",
    "{} being admired by a large crowd in a museum",
    "the moment before discovery, showing {} hidden in foliage",
    "{} soaring over a dense urban sprawl",
    "inside a giant crystal cavern, reflecting light off {}",
    "{} overlooking a vast, shimmering desert",
    "a candid, reportage photo of {} at work",
    "the reflection of {} in a puddle on a rainy street",
    "{} relaxing next to a campfire under the stars",
    "a surreal landscape where gravity seems to affect {} differently",
    "{} appearing in a dream sequence, slightly distorted",
    "behind bars in an ornate, Victorian cage, the pathetic {}",
    "{} engaged in a silent, meaningful conversation with another entity",
    "a forgotten relic, {} sits on a dusty shelf",

    # V. Technical & Cinematic
    "an extreme close-up (ECU) on the texture of {}",
    "{} captured with a wide-angle lens, showing distortion",
    "a shallow depth of field (bokeh) shot of {}",
    "panoramic vista capturing {} in the distance",
    "{} photographed with a 70mm lens, cinematic feel",
    "a Dutch angle (canted frame) shot of {}",
    "hyperfocal distance setting, ensuring clarity across {}",
    "{} viewed from a high-angle shot (bird's-eye view)",
    "a long exposure photograph capturing the movement of {}",
    "{} framed by an archway (natural framing)",
    "tilt-shift effect applied to a photograph of {}",
    "a macro shot emphasizing the tiny details of {}",
    "lens flare effects catching the edge of {}",
    "{} captured with a fisheye lens",
    "a double exposure image combining a landscape with {}",
]

BEST_GHIBLI_STYLE_TEMPLATES = [
    "in the style of {}, a rainy window overlooking a park",
    "{} style depiction of a cat on a stone wall",
    "{} style shelf filled with old books",
    "a bird perched on a metal fence, {} style",
    "a cluster of clouds in a wide sky, {} style",
    "in the style of {}, a person looking at a reflection",
    "a night sky over a dark forest, style of {}",
    "in the style of {}, a row of empty park benches",
    "a single lit candle in a dark hallway, {} style",
    "{} style view of a distant horizon over the sea",
    "{} style silhouette of a city at twilight",
    "a train track disappearing into the distance, style of {}",
    "a person holding a small bird, {} style",
    "a weathered wooden gate in a hedge, style of {}",
    "in the style of {}, a high-angle view of a dining table",
    "in the style of {}, an old clock on a mantelpiece",
    "a winding dirt road through a valley, style of {}",
    "in the style of {}, a window with partially closed shutters",
    "in the style of {}, a person writing a letter",
    "in the style of {}, a person standing on a balcony",
    "{} style portrait of a person in a workshop",
    "a wooden porch overlooking a garden, style of {}",
    "in the style of {}, a person reading by a window",
    "in the style of {}, a person leaning against a tree",
    "a still life of a loaf of bread, {} style",
]

GOOD_ARTIST_STYLE_TEMPLATES = [
    "in the style of {}, a rainy window overlooking a park",
    "{} style depiction of a cat on a stone wall",
    "{} style shelf filled with old books",
    "a bird perched on a metal fence, {} style",
    "a cluster of clouds in a wide sky, {} style",
    "in the style of {}, a person looking at a reflection",
    "a night sky over a dark forest, style of {}",
    "a simple wooden chair in an empty room, {} style",
    "{} style close-up of a glass of water on a table",
    "a lone tree in a vast snowy field, style of {}",
    "in the style of {}, sunlight filtering through tall grass",
    "a pair of worn leather boots, {} style",
    "{} style study of a jagged mountain peak",
    "a staircase spiraling into shadow, style of {}",
    "in the style of {}, a row of empty park benches",
    "a single lit candle in a dark hallway, {} style",
    "{} style depiction of a rocky coastline at high tide",
    "a bicycle leaning against a brick wall, style of {}",
    "in the style of {}, a person walking through thick fog",
    "a bowl of citrus fruit in harsh light, {} style",
    "{} style view of a distant horizon over the sea",
    "an open book with turning pages, style of {}",
    "in the style of {}, a series of arched doorways",
    "a forest floor covered in fallen leaves, {} style",
    "{} style portrait of an anonymous traveler",
    "a stone bridge crossing a silent creek, style of {}",
    "in the style of {}, a tangled thicket of wild vines",
    "a single white flower in a ceramic vase, {} style",
    "{} style silhouette of a city at twilight",
    "a train track disappearing into the distance, style of {}",
    "in the style of {}, a marketplace with empty stalls",
    "a person holding a small bird, {} style",
    "{} style study of ripples on a pond",
    "a weathered wooden gate in a hedge, style of {}",
    "in the style of {}, a high-angle view of a dining table",
    "a scattered deck of playing cards, {} style",
    "{} style depiction of a stormy sky over a plain",
    "a portrait of a person looking at the stars, style of {}",
    "in the style of {}, an old clock on a mantelpiece",
    "a group of shadows on a concrete floor, {} style",
    "{} style close-up of a butterfly on a stone",
    "a winding dirt road through a valley, style of {}",
    "in the style of {}, a person sitting on a pier",
    "a basket of woven reeds in the sun, {} style",
    "{} style study of a cracked plaster wall",
    "a line of laundry drying in the wind, style of {}",
    "in the style of {}, a lantern hanging from a branch",
    "a person draped in a heavy wool blanket, {} style",
    "{} style depiction of a field of tall sunflowers",
    "a stack of vintage suitcases, style of {}",
    "in the style of {}, a window with partially closed shutters",
    "a path of stepping stones through moss, {} style",
    "{} style portrait of a person in a heavy coat",
    "a row of streetlights on a misty night, style of {}",
    "in the style of {}, a close-up of tree bark",
    "a wooden boat drifting on calm water, {} style",
    "{} style view through a dusty attic window",
    "a person standing under a large umbrella, style of {}",
    "in the style of {}, a collection of smooth river stones",
    "a desert canyon with sharp shadows, {} style",
    "{} style study of a bird's nest in a tree",
    "a fireplace with glowing embers, style of {}",
    "in the style of {}, a person writing a letter",
    "a field of lavender under a pale moon, {} style",
    "{} style depiction of a distant lighthouse beam",
    "a cup of steaming tea on a windowsill, style of {}",
    "in the style of {}, a group of horses in a paddock",
    "a portrait of a person with silver hair, {} style",
    "{} style study of a spiderweb in the rain",
    "a quiet courtyard with a small fountain, style of {}",
    "in the style of {}, a person standing on a balcony",
    "a row of pine trees against a gray sky, {} style",
    "{} style depiction of a key on a ring",
    "a vast canyon under a midday sun, style of {}",
    "in the style of {}, a person looking through a telescope",
    "a cluster of grapes on a vine, {} style",
    "{} style study of a violin in its case",
    "a person standing in a field of tall wheat, style of {}",
    "in the style of {}, a series of waves hitting rocks",
    "a simple stone cottage in the hills, {} style",
    "{} style portrait of a person in a workshop",
    "a wooden porch overlooking a garden, style of {}",
    "in the style of {}, a person walking along a shoreline",
    "a collection of old keys on a table, {} style",
    "{} style study of a thunderstorm in the distance",
    "a single park bench under a streetlamp, style of {}",
    "in the style of {}, a person reading by a window",
    "a portrait of a person with a scarf, {} style",
    "{} style depiction of a forest in autumn",
    "a stone wall covered in climbing ivy, style of {}",
    "in the style of {}, a view of a valley from a cliff",
    "a person standing in a sunbeam, {} style",
    "{} style study of a seashell on the sand",
    "a row of colored houses on a hill, style of {}",
    "in the style of {}, a person leaning against a tree",
    "a still life of a loaf of bread, {} style",
    "{} style depiction of a mountain lake at sunset",
    "a portrait of a person in deep thought, style of {}",
    "in the style of {}, a landscape of rolling hills",
    "a person walking into the light, {} style"
]


DIVERSE_ARTIST_STYLE_TEMPLATES = [
    "in the style of {}, a vast open landscape",
    "a portrait of a person in the style of {}",
    "{} style study of a single oak tree",
    "a bustling city street, style of {}",
    "in the style of {}, a mountain range at dawn",
    "a person standing in a doorway, {} style",
    "{} style painting of a bowl of fruit",
    "a view of the ocean from a cliff, style of {}",
    "an interior of a quiet cafe in the style of {}",
    "{} style close-up of a flower blooming",
    "a forest path winding into the distance, style of {}",
    "in the style of {}, a rainy window overlooking a park",
    "a child playing with a wooden toy, {} style",
    "{} style depiction of a cat on a stone wall",
    "a marketplace with various vendors, style of {}",
    "in the style of {}, a row of old houses by a river",
    "a lone figure walking in a field, {} style",
    "{} style desert landscape with sand dunes",
    "a bridge over a small stream, style of {}",
    "in the style of {}, a group of people in a square",
    "a stone castle on a grassy hill, {} style",
    "{} style shelf filled with old books",
    "a lighthouse standing against the wind, style of {}",
    "in the style of {}, a horse running through a meadow",
    "a window looking out onto a garden, {} style",
    "{} style narrow alleyway in an old town",
    "a person reading under a lamp, style of {}",
    "in the style of {}, a snow-covered village at night",
    "a harbor with several small boats, {} style",
    "{} style close-up of a human hand",
    "fields of wheat under a cloudy sky, style of {}",
    "in the style of {}, a stone fireplace in a room",
    "a sunrise over a quiet lake, {} style",
    "{} style portrait of an elderly person",
    "a dense cluster of wild ferns, style of {}",
    "in the style of {}, a table set for a simple meal",
    "a bird perched on a metal fence, {} style",
    "{} style winding road through the hills",
    "a waterfall in a shaded glen, style of {}",
    "in the style of {}, a person looking at a reflection",
    "a cluster of clouds in a wide sky, {} style",
    "{} style cottage with a flower garden",
    "a busy train station platform, style of {}",
    "in the style of {}, antique glass bottles",
    "a park bench under a large oak tree, {} style",
    "{} style portrait of a person in profile",
    "a night sky over a dark forest, style of {}",
    "in the style of {}, a city skyline reflected in water",
    "a simple wooden chair in an empty room, {} style",
    "{} style dog sleeping by a doorway",
    "a valley viewed from a high peak, style of {}",
    "in the style of {}, a stone statue in a courtyard",
    "a person walking through a crowd, {} style",
    "{} style ship on the open sea",
    "a basket of freshly picked apples, style of {}",
    "in the style of {}, a field of wildflowers",
    "a staircase leading up to a landing, {} style",
    "{} style portrait with dramatic side lighting",
    "a campfire burning in the dusk, style of {}",
    "in the style of {}, a small boat tied to a dock",
    "a group of trees in autumn colors, {} style",
    "{} style person working at a desk",
    "a cobblestone street after the rain, style of {}",
    "in the style of {}, a mountain stream with rocks",
    "a close-up of a butterfly on a leaf, {} style",
    "{} style desert oasis with palm trees",
    "a courtyard with a central fountain, style of {}",
    "in the style of {}, a person carrying a heavy load",
    "a sunset over a flat horizon, {} style",
    "{} style collection of sea shells on sand",
    "a bridge crossing a wide river, style of {}",
    "in the style of {}, a forest floor with needles",
    "a portrait of a young child, {} style",
    "{} style town square with a clock tower",
    "a single candle flame in the dark, style of {}",
    "in the style of {}, a person looking at the sea",
    "a row of trees along a fence line, {} style",
    "{} style stack of ceramic plates",
    "a view through a forest canopy, style of {}",
    "in the style of {}, a stone path leading to a gate",
    "a portrait of a person smiling, {} style",
    "{} style city street at twilight",
    "a field of tall grass in the wind, style of {}",
    "in the style of {}, a quiet study with a fireplace",
    "a dock extending into a misty bay, {} style",
    "{} style close-up of a weathered door",
    "a mountain peak above the clouds, style of {}",
    "in the style of {}, a person in a sunlit hall",
    "a still life with a pitcher and bowl, {} style",
    "{} style winding river through a plain",
    "a portrait of a person in a hat, style of {}",
    "in the style of {}, a forest in the morning fog",
    "a group of houses on a steep hill, {} style",
    "{} style single red rose in a glass",
    "a person walking a dog in a park, style of {}",
    "in the style of {}, a rocky shoreline with pools",
    "a sunlit kitchen with open windows, {} style",
    "{} style starry sky above a silent desert",
    "a final study of light and shadow, style of {}",
    "in the style of {}, an empty park at midnight"
]

CUSTOM_SD3_TEMPLATES = [
    "A professional cinematic shot of {}. High dynamic range, volumetric lighting, 8k resolution, detailed textures, and shallow depth of field.",
    "A high-end studio portrait of {}. Professional three-point lighting, neutral background, sharp focus, and hyper-realistic surface rendering.",
    "A candid, wide-angle street photo of {}. Natural daylight, urban atmosphere, realistic shadows, and high-quality lens grit.",
    "{} captured during golden hour. Warm, directional sunlight, long shadows, atmospheric haze, and soft rim lighting.",
    "A hyper-detailed macro close-up of {}. Extreme texture clarity, microscopic detail, and soft bokeh background.",
    "A museum-quality oil painting of {}. Thick impasto brushstrokes, rich pigment textures, and classical composition.",
    "A digital concept art piece of {}. Polished finish, epic scale, masterful color theory, and professional illustration quality.",
    "A clean, minimalist vector illustration of {}. Bold shapes, flat design aesthetic, high-contrast colors, and sharp edges.",
    "An expressive watercolor painting of {}. Fluid washes, paper texture, delicate splatters, and soft transitions.",
    "{} in a futuristic cyberpunk style. Vibrant neon lighting, high-contrast shadows, and polished metallic reflections.",
    "A classical white marble statue of {}. Smooth polished stone, intricate carvings, soft subsurface scattering, and dramatic museum lighting.",
    "A highly detailed steampunk version of {}. Polished brass, intricate clockwork, steam effects, and high-quality metallic luster.",
    "An ethereal, glowing depiction of {}. Soft luminescence, particles of light, dreamlike atmosphere, and magical aura.",
    "{} carved from dark mahogany wood. Visible grain, polished finish, organic textures, and warm ambient lighting.",
    "A black and white film noir scene featuring {}. High contrast, dramatic chiaroscuro lighting, smoky atmosphere, and grainy film texture.",
    "A high-fashion editorial spread featuring {}. Avant-garde styling, sharp focus, professional color grading, and minimalist studio backdrop.",
    "{} positioned within a vast, epic landscape. Grand scale, atmospheric perspective, high-detail environment, and cinematic wide-angle.",
    "{} in a 1980s retro-futuristic style. Chrome reflections, vibrant gradients, grid horizons, and stylized glow.",
    "{} depicted as a legendary mythological figure. Ornate detailing, divine lighting, gold leaf accents, and symmetrical composition.",
    "A high-energy pop art illustration of {}. Bold halftone patterns, vibrant saturated colors, and clean ink outlines."
]